title: Configurando minimal Rapha Jaime DEV
logo: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT686aevR5JdfmrsxDmEVhLiYLyRNXjm5Nk-A&usqp=CAU
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
