title: Minimal theme
logo: https://www.google.com/imgres?imgurl=https%3A%2F%2Fpraxisdesenvolvimento.com.br%2Fassets%2Flogo-qualificadf.png&tbnid=dLvY7wJvmnQ1TM&vet=12ahUKEwivl9m3vPaAAxWErpUCHeaBCbMQMygBegQIARBS..i&imgrefurl=https%3A%2F%2Fpraxisdesenvolvimento.com.br%2Fqualificadf%2F&docid=zzpyCogk957DiM&w=356&h=79&q=qualifica%20df&ved=2ahUKEwivl9m3vPaAAxWErpUCHeaBCbMQMygBegQIARBS
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
